site: Seki
title: SekiðŸ—¡ï¸
greetings: Hi ðŸ‘‹
description: >-
  just a simple, personal blog
lang: en-US
timezone:  West Africa/Nigeria
github-username: obasekiosa
repo: https://github.com/obasekiosa.github.io.git # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: obasekiosa # replace with your disqus shortname

author:
  name: obasekiosa
  bio: just a minimalist, personal blog
  github: obasekiosa # github username

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
#url: https://obasekiosa.github.io # Domain Name of host. [username].github.io for github pages
permalink: pretty

exclude:
  - README.md
  - package.json
  - yarn.lock
  - tailwind.config.js
  - postcss.config.js
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-postcss-v2


